toy = {'레고': '12000', '기차':'15000', '로봇':'9000', '지구본':'13500', '시계':'10000'}
a = toy['레고']
b = toy['기차']
c = toy['로봇']
d = toy['지구본']
e = toy['시계']
A = int(a)
B = int(b)
C = int(c)
D = int(d)
E = int(e)
sell = {'레고': 23, '기차': 50, '로봇': 27, '지구본': 15, '시계': 57}
v = sell['레고']
w = sell['기차']
x = sell['로봇']
y = sell['지구본']
z = sell['시계']
V = A * v
W = B * w
X = C * x
Y = D * y
Z = E * z
sum = V + W + X + Y + Z
print(sum)
